name: Build, publish and deploy Tololus main site to Simply

on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish
        
      - name: Test with .NET
        run: dotnet test

      - name: Deploy to Simply        
        uses: talunzhang/auto-web-deploy@v1.0.1
        with:
          website-name: tololus-001-site1
          server-computer-name: https://win9081.site4now.net:8172
          server-username: tololus-001
          server-password: "Tololus=0"
          source-path: '\Tololus\bin\release\'
      - name: Migrate
        run: |
          cd tololus
          dotnet tool install --global dotnet-ef
          -context: 'TololusContext'
          dotnet ef database update --connection  'Data Source=SQL9001.site4now.net;Database=db_aa6158_tololus;User Id=db_aa6158_tololus_admin;Password=Tololus=0;' --context TololusContext
          
